#!/usr/bin/env python
# -*- coding: utf-8 -*-

import rospy
from std_srvs.srv import Trigger

class CoreModeDecider():
    def __init__(self):
        rospy.wait_for_service('/traffic_light')
        try:
            self.client_traffic_light = rospy.ServiceProxy('/traffic_light', Trigger)
            response = self.client_traffic_light()
            if response.success:
                print("[SUCCESS] Mission 1: Traffic Light Mission")
            if not response.success:
                raise Exception(response.message)
        except rospy.ServiceException as e:
            print("Service call failed: %s"%e)

if __name__ == '__main__':
    try:
        rospy.init_node('core')
        node = CoreModeDecider()
    except rospy.ROSInterruptException():
        pass
